"""Add DomainSettings

Revision ID: 803539d00f64
Revises: 8d937cd3c427
Create Date: 2026-08-10 21:02:01.336551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803539d00f64'
down_revision: Union[str, Sequence[str], None] = '8d937cd3c427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('contamination_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_settings_domain'), 'domain_settings', ['domain'], unique=True)
    op.create_index(op.f('ix_domain_settings_id'), 'domain_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_settings_id'), table_name='domain_settings')
    op.drop_index(op.f('ix_domain_settings_domain'), table_name='domain_settings')
    op.drop_table('domain_settings')
    # ### end Alembic commands ###
