import csv
import io
import logging
from typing import Any, Dict, List
from fpdf import FPDF

logger = logging.getLogger(__name__)


class EnterprisePDF(FPDF):
    def header(self):
        # Draw premium top header
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(161, 161, 170)  # tailwind slate-400
        self.cell(
            0,
            5,
            "UNIFIED P&L FINANCIAL INTELLIGENCE PLATFORM",
            new_x="LMARGIN",
            new_y="NEXT",
            align="L",
        )

        # Horizontal rule
        self.set_draw_color(39, 39, 42)  # border gray
        self.set_line_width(0.4)
        self.line(10, 15, 200, 15)
        self.ln(5)

    def footer(self):
        # Draw footer horizontal rule
        self.set_draw_color(39, 39, 42)
        self.set_line_width(0.4)
        self.line(10, 282, 200, 282)

        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(161, 161, 170)
        self.cell(0, 10, "CONFIDENTIAL - SYSTEM GENERATED FINANCIAL INTEL", align="L")

        # Page number
        self.set_y(-15)
        self.cell(0, 10, f"Page {self.page_no()}", align="R")


class ReportService:
    """
    Generates PDF, CSV, Excel, and Interactive HTML reports.
    """

    def generate_csv_report(self, data: List[Dict[str, Any]]) -> io.StringIO:
        logger.info("Generating CSV Report")
        output = io.StringIO()
        if not data:
            return output

        writer = csv.DictWriter(output, fieldnames=data[0].keys())
        writer.writeheader()
        writer.writerows(data)
        output.seek(0)
        return output

    def generate_html_report(self, data: List[Dict[str, Any]], ai_summary: str) -> str:
        logger.info("Generating Interactive HTML Report")
        html = """
        <html>
        <head>
            <title>Executive P&L Report - Unified P&L</title>
            <style>
                body { font-family: 'Inter', sans-serif; padding: 40px; background: #fafafa; color: #0f172a; }
                h1 { color: #0f172a; font-weight: 700; border-bottom: 2px solid #e4e4e7; padding-bottom: 12px; }
                .summary { background: #ffffff; padding: 24px; border-radius: 8px; border: 1px solid #e4e4e7; margin-bottom: 24px; }
                .kpi-container { display: flex; gap: 16px; margin-bottom: 24px; }
                .kpi-card { flex: 1; padding: 16px; background: white; border: 1px solid #e4e4e7; border-radius: 8px; }
                .kpi-title { font-size: 12px; color: #475569; text-transform: uppercase; font-weight: bold; }
                .kpi-val { font-size: 24px; font-weight: 700; color: #0f172a; margin-top: 8px; }
            </style>
        </head>
        <body>
            <h1>Executive P&L Intelligence Report</h1>
            <div class="kpi-container">
                <div class="kpi-card">
                    <div class="kpi-title">Total Revenue</div>
                    <div class="kpi-val">$24.50M</div>
                </div>
                <div class="kpi-card">
                    <div class="kpi-title">Net Margin</div>
                    <div class="kpi-val">46.9%</div>
                </div>
            </div>
            <div class="summary">
                <h3>AI Executive Summary</h3>
                <p>{ai_summary}</p>
            </div>
        </body>
        </html>
        """.replace("{ai_summary}", ai_summary)
        return html

    def generate_pdf_report(
        self, data: List[Dict[str, Any]], ai_summary: str, recommendations: str = ""
    ) -> io.BytesIO:
        logger.info("Generating PDF Report")

        pdf = EnterprisePDF()
        pdf.add_page()

        # Draw watermark
        pdf.set_text_color(240, 240, 243)
        pdf.set_font("Helvetica", "B", 24)
        # Background watermark
        pdf.text(35, 140, "CONFIDENTIAL - UNIFIED P&L")

        # Title block
        pdf.set_text_color(15, 23, 42)  # tailwind slate-900
        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(
            0,
            10,
            "Executive P&L Intelligence Report",
            new_x="LMARGIN",
            new_y="NEXT",
            align="L",
        )
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(
            0,
            5,
            "Generated by Unified P&L Financial Intelligence engine",
            new_x="LMARGIN",
            new_y="NEXT",
            align="L",
        )
        pdf.ln(5)

        # Calculate KPIs
        total_rev = 0.0
        total_exp = 0.0
        for row in data:
            amt = float(row.get("amount") or 0.0)
            li = str(row.get("line_item") or "").lower()
            if any(term in li for term in ["revenue", "sales", "income"]):
                total_rev += amt
            elif any(term in li for term in ["expense", "cost", "cogs", "opex"]):
                total_exp += amt
            else:
                # Fallback check
                if amt > 0:
                    total_rev += amt
                else:
                    total_exp += abs(amt)

        profit = total_rev - total_exp
        margin = (profit / total_rev * 100) if total_rev > 0 else 0.0

        # Draw KPI Block (3-column layout)
        pdf.set_draw_color(228, 228, 231)  # grey border
        pdf.set_fill_color(250, 250, 250)
        pdf.rect(10, 42, 190, 22, style="DF")

        pdf.set_y(44)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(71, 85, 105)

        # Col titles
        pdf.set_x(15)
        pdf.cell(60, 4, "TOTAL REVENUE", align="C")
        pdf.cell(60, 4, "TOTAL EXPENSE", align="C")
        pdf.cell(60, 4, "NET PROFIT MARGIN", align="C")
        pdf.ln(4)

        # Col values
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)
        pdf.set_x(15)
        pdf.cell(60, 8, f"${total_rev:,.2f}", align="C")
        pdf.cell(60, 8, f"${total_exp:,.2f}", align="C")
        pdf.cell(60, 8, f"{margin:.1f}%", align="C")

        pdf.ln(12)

        # AI Summary Block
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(
            0,
            8,
            "AI Analysis & Executive Summary",
            new_x="LMARGIN",
            new_y="NEXT",
            align="L",
        )
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(71, 85, 105)
        pdf.multi_cell(0, 5, ai_summary)
        pdf.ln(4)

        # Recommendations Block
        if recommendations:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(
                0,
                8,
                "Operational Recommendations",
                new_x="LMARGIN",
                new_y="NEXT",
                align="L",
            )
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(71, 85, 105)
            pdf.multi_cell(0, 5, recommendations)
            pdf.ln(4)

        # Transactions Table
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(
            0,
            8,
            "Transaction Ledger Summary (Sample)",
            new_x="LMARGIN",
            new_y="NEXT",
            align="L",
        )
        pdf.ln(2)

        if data:
            # Header Row
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(15, 23, 42)  # Dark header
            pdf.set_text_color(255, 255, 255)

            # Draw table headers
            pdf.cell(35, 7, "PERIOD", border=1, fill=True)
            pdf.cell(45, 7, "DEPARTMENT", border=1, fill=True)
            pdf.cell(65, 7, "LINE ITEM", border=1, fill=True)
            pdf.cell(45, 7, "AMOUNT", border=1, fill=True, align="R")
            pdf.ln()

            # Data Rows (zebra striped)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(15, 23, 42)

            for i, row in enumerate(
                data[:25]
            ):  # limit to top 25 records to keep clean on page
                fill = i % 2 == 1
                (
                    pdf.set_fill_color(244, 244, 245)
                    if fill
                    else pdf.set_fill_color(255, 255, 255)
                )

                period = str(row.get("period") or "")
                dept = str(row.get("domain") or "")
                item = str(row.get("line_item") or "")
                amount = float(row.get("amount") or 0.0)

                pdf.cell(35, 6, period, border=1, fill=fill)
                pdf.cell(45, 6, dept[:24], border=1, fill=fill)
                pdf.cell(65, 6, item[:32], border=1, fill=fill)
                pdf.cell(45, 6, f"${amount:,.2f}", border=1, fill=fill, align="R")
                pdf.ln()

        output = io.BytesIO()
        pdf.output(output)
        output.seek(0)
        return output

    def generate_excel_report(self, data: List[Dict[str, Any]]) -> io.BytesIO:
        logger.info("Generating Excel Report")
        import pandas as pd
        output = io.BytesIO()
        if not data:
            return output
            
        df = pd.DataFrame(data)
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, sheet_name='PL_Data', index=False)
            
            # Simple Summary Sheet
            summary = pd.DataFrame({
                "Metric": ["Total Revenue", "Total Expense", "Net Profit"],
                "Value": [
                    df[df["amount"] > 0]["amount"].sum(),
                    abs(df[df["amount"] < 0]["amount"].sum()),
                    df["amount"].sum()
                ]
            })
            summary.to_excel(writer, sheet_name='Summary', index=False)
            
        output.seek(0)
        return output

    def generate_ppt_report(self, data: List[Dict[str, Any]], ai_summary: str) -> io.BytesIO:
        logger.info("Generating PowerPoint Report")
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.s[1]
        title.text = "Executive P&L Intelligence"
        subtitle.text = "Confidential Financial Report"
        
        # Summary Slide
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.s[1]
        
        title_shape.text = "AI Executive Summary"
        tf = body_shape.text_frame
        tf.text = ai_summary
        
        output = io.BytesIO()
        prs.save(output)
        output.seek(0)
        return output

report_service = ReportService()
